### ISSUE TITLE
Генерировать правильные имена комбинаторов

### ISSUE THREAD

**Issue by s9gf4ult** [astynax/hemmet#1]
Если написать имя тега, например:

`<:block>span.elem` 

то получим комбинатор с именем `span` 

```haskell 
span "block__elem" $ pure ()
```

А надо `spanc_`. По соглашению, имена функций для генерации тегов состоят из `имя_тега <> "c_"`

`_` из `react-flux`, а `c` говорит, что функция принимает аргументом `Class`.

**Comment by astynax** [comment]
Solved in 2de44b8b93f2a05a9559487a0f6c5d1e2aef88e8
