### ISSUE TITLE
Emmet does suport any order of DOM attributes, while Hemmet does not

### ISSUE THREAD

**Issue by uhbif19** [astynax/hemmet#25]
Example, working in Emmet: `a.b#a.c`

**Comment by uhbif19** [comment]
Possible realization: https://t.me/haskell_learn/100691

**Comment by astynax** [comment]
There is no goal to be 100% Emmet-compatible. Strict order of "id and then classes" is a design decision.

**Comment by uhbif19** [comment]
@astynax Should then I use strict order for multiplicity too?

**Comment by astynax** [comment]
It will be nice to have a multiplier as the very first item (prefix): `3*a`. But it looks incompatible with Emmet. So let it be the suffix.

**Comment by uhbif19** [comment]
@astynax Suffix meaning, after id and class?

**Comment by astynax** [comment]
Yep, `#id.class1.class2*3`

**Comment by uhbif19** [comment]
@astynax So, this issue should probably be closed?
